python train.py \
--name face_pix2pix_alpha_bs \
--display_port 12345 \
--input_nc 9 \
--lambda_L1 100 \
--no_dropout \
--objpath ./result_obj \
--gpu_ids 9 \
--dataroot /home/ICT2000/jli/local/data \
--model pix2pixbs \
--direction AtoB \
--load_size 256 \
--no_flip \
--num_threads 0 \
--jsonfile ./train_all_data.json \
--alternate_epoch 30 \
--alternate_iter 5 \
--display_freq 300 \
--print_freq 10
